// Generates src/renderer/icons.ts from @gravity-ui/icons.
//
// Only the icons listed here are inlined, which keeps the bundle to a few KB and
// avoids shipping an icon font (the renderer runs under a CSP of 'self', so a web
// font would have to be vendored anyway).
// Usage: node tools/gen-icons.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const svgDir = path.join(root, 'node_modules', '@gravity-ui', 'icons', 'svgs');

/** semantic name -> gravity-ui icon file */
const ICONS = {
  play: 'play-fill',
  playAll: 'bars-play',
  stop: 'stop-fill',
  pause: 'pause',
  analyze: 'magic-wand',
  exportWav: 'file-arrow-down',
  exportLabel: 'file-text',
  open: 'folder-open',
  save: 'floppy-disk',
  settings: 'gear',
  add: 'plus',
  remove: 'xmark',
  reset: 'arrow-rotate-left',
  merge: 'chevrons-collapse-horizontal',
  split: 'chevrons-expand-horizontal',
  warning: 'triangle-exclamation',
  voice: 'person-speaker',
  drop: 'arrow-down-to-line',
  edit: 'pencil',
};

const entries = [];
const missing = [];

for (const [name, file] of Object.entries(ICONS)) {
  const full = path.join(svgDir, `${file}.svg`);
  if (!fs.existsSync(full)) { missing.push(`${name} -> ${file}.svg`); continue; }
  const raw = fs.readFileSync(full, 'utf8');

  const viewBox = raw.match(/viewBox="([^"]+)"/)?.[1];
  if (!viewBox) throw new Error(`${file}.svg has no viewBox`);

  // Keep only the drawing instructions; the wrapper <svg> is rebuilt at runtime.
  const inner = raw
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .trim();
  if (!inner) throw new Error(`${file}.svg has no content`);

  entries.push({ name, file, viewBox, inner });
}

if (missing.length > 0) {
  console.error('these icons were not found in @gravity-ui/icons:\n  ' + missing.join('\n  '));
  process.exit(1);
}

const body = entries
  .map((e) => `  // ${e.file}.svg\n  ${e.name}: { viewBox: ${JSON.stringify(e.viewBox)}, path: ${JSON.stringify(e.inner)} },`)
  .join('\n');

const out = `// AUTO-GENERATED by tools/gen-icons.mjs from @gravity-ui/icons.
// Do not edit by hand; add a name to the generator's ICONS map and re-run
// \`npm run gen-icons\` instead.
//
// The path data below is from @gravity-ui/icons, MIT licensed,
// Copyright (c) 2022 YANDEX LLC. See THIRD-PARTY-NOTICES.md.

export interface IconDef {
  viewBox: string;
  /** Inner SVG markup; every shape is filled with currentColor. */
  path: string;
}

export const ICONS = {
${body}
} as const satisfies Record<string, IconDef>;

export type IconName = keyof typeof ICONS;
`;

fs.writeFileSync(path.join(root, 'src', 'renderer', 'icons.ts'), out);
const bytes = entries.reduce((n, e) => n + e.inner.length, 0);
console.log(`inlined ${entries.length} icons (${bytes} bytes of path data)`);
