// Generates src/main/engine/tables.js from the Open JTalk C rule headers.
// Run: node tools/gen-tables.js <path-to-open_jtalk-1.11>
const fs = require('fs');
const path = require('path');

const root = process.argv[2];
if (!root) { console.error('usage: node tools/gen-tables.js <open_jtalk source dir>'); process.exit(1); }

// Pull the string literals out of a `static const char *NAME[] = { ... };` block.
function readList(file, name) {
  const src = fs.readFileSync(file, 'utf8');
  const start = src.indexOf(`*${name}[] = {`);
  if (start < 0) throw new Error(`${name} not found in ${file}`);
  const end = src.indexOf('};', start);
  const body = src.slice(src.indexOf('{', start) + 1, end);
  const out = [];
  // Match either "quoted string" or a bare NULL, in source order.
  const re = /"((?:[^"\\]|\\.)*)"|\bNULL\b/g;
  let m;
  while ((m = re.exec(body)) !== null) out.push(m[1] === undefined ? null : m[1]);
  // Trim the trailing all-NULL terminator row.
  while (out.length && out[out.length - 1] === null) out.pop();
  return out;
}

function chunk(arr, n) {
  const out = [];
  for (let i = 0; i < arr.length; i += n) out.push(arr.slice(i, i + n));
  return out;
}

const jp = path.join(root, 'jpcommon', 'jpcommon_rule_utf_8.h');
const nj = path.join(root, 'njd2jpcommon', 'njd2jpcommon_rule_utf_8.h');

const moraRows = chunk(readList(jp, 'jpcommon_mora_list'), 3);
const unvoice = Object.fromEntries(chunk(readList(jp, 'jpcommon_unvoice_list'), 2));
const jpPos = Object.fromEntries(chunk(readList(jp, 'jpcommon_pos_list'), 2));
const jpCform = Object.fromEntries(chunk(readList(jp, 'jpcommon_cform_list'), 2));
const jpCtype = Object.fromEntries(chunk(readList(jp, 'jpcommon_ctype_list'), 2));
const njdPos = chunk(readList(nj, 'njd2jpcommon_pos_list'), 5);
const njdCform = Object.fromEntries(chunk(readList(nj, 'njd2jpcommon_cform_list'), 2));
const njdCtype = Object.fromEntries(chunk(readList(nj, 'njd2jpcommon_ctype_list'), 2));

const j = (v) => JSON.stringify(v, null, 2);
const out = `// AUTO-GENERATED by tools/gen-tables.js from Open JTalk 1.11 rule headers.
// Do not edit by hand; re-run the generator instead.
// Source: open_jtalk-1.11/{jpcommon,njd2jpcommon}/*_rule_utf_8.h (BSD-3-Clause, Nagoya Institute of Technology)

'use strict';

// [mora, consonant, vowel] in the original table order. Order matters: lookup is a
// longest-prefix match performed by scanning top to bottom, exactly as the C does.
const MORA_LIST = ${j(moraRows)};

const UNVOICE = ${j(unvoice)};

// jpcommon: descriptive name -> numeric code used in the label
const JP_POS = ${j(jpPos)};
const JP_CFORM = ${j(jpCform)};
const JP_CTYPE = ${j(jpCtype)};

// njd2jpcommon: mecab POS quadruple -> jpcommon descriptive name
const NJD_POS = ${j(njdPos)};
const NJD_CFORM = ${j(njdCform)};
const NJD_CTYPE = ${j(njdCtype)};

module.exports = { MORA_LIST, UNVOICE, JP_POS, JP_CFORM, JP_CTYPE, NJD_POS, NJD_CFORM, NJD_CTYPE };
`;

fs.writeFileSync(path.join(__dirname, '..', 'src', 'main', 'engine', 'tables.js'), out);
console.log(`mora=${moraRows.length} unvoice=${Object.keys(unvoice).length} jpPos=${Object.keys(jpPos).length} njdPos=${njdPos.length} njdCtype=${Object.keys(njdCtype).length} njdCform=${Object.keys(njdCform).length}`);
