// Generates src/main/engine/tables.ts from the Open JTalk C rule headers.
// Usage: node tools/gen-tables.mjs <path-to-open_jtalk-1.11>
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = process.argv[2];
if (!root) { console.error('usage: node tools/gen-tables.mjs <open_jtalk source dir>'); process.exit(1); }

// Pull the string literals out of a `static const char *NAME[] = { ... };` block.
function readList(file, name) {
  const src = fs.readFileSync(file, 'utf8');
  const start = src.indexOf(`*${name}[] = {`);
  if (start < 0) throw new Error(`${name} not found in ${file}`);
  const end = src.indexOf('};', start);
  const body = src.slice(src.indexOf('{', start) + 1, end);
  const out = [];
  const re = /"((?:[^"\\]|\\.)*)"|\bNULL\b/g;
  let m;
  while ((m = re.exec(body)) !== null) out.push(m[1] === undefined ? null : m[1]);
  return out;
}

// Chunk into fixed-width rows, padding a short final row. A legitimate row may end
// in NULL (e.g. a vowel-only mora), so rows are only dropped when *entirely* NULL --
// that is the table's terminator, not data.
function chunk(arr, n) {
  const rows = [];
  for (let i = 0; i < arr.length; i += n) {
    const row = arr.slice(i, i + n);
    while (row.length < n) row.push(null);
    if (row.every((v) => v === null)) continue;
    rows.push(row);
  }
  return rows;
}

const jp = path.join(root, 'jpcommon', 'jpcommon_rule_utf_8.h');
const nj = path.join(root, 'njd2jpcommon', 'njd2jpcommon_rule_utf_8.h');

const moraRows = chunk(readList(jp, 'jpcommon_mora_list'), 3);
const unvoice = Object.fromEntries(chunk(readList(jp, 'jpcommon_unvoice_list'), 2));
const jpPos = Object.fromEntries(chunk(readList(jp, 'jpcommon_pos_list'), 2));
const jpCform = Object.fromEntries(chunk(readList(jp, 'jpcommon_cform_list'), 2));
const jpCtype = Object.fromEntries(chunk(readList(jp, 'jpcommon_ctype_list'), 2));
const njdPos = chunk(readList(nj, 'njd2jpcommon_pos_list'), 5);
const njdCform = Object.fromEntries(chunk(readList(nj, 'njd2jpcommon_cform_list'), 2));
const njdCtype = Object.fromEntries(chunk(readList(nj, 'njd2jpcommon_ctype_list'), 2));

const j = (v) => JSON.stringify(v, null, 2);
const out = `// SPDX-License-Identifier: BSD-3-Clause
//
// AUTO-GENERATED by tools/gen-tables.mjs from the Open JTalk 1.11 rule headers.
// Do not edit by hand; re-run \`npm run gen-tables -- <open_jtalk source dir>\` instead.
//
// This file is derived from Open JTalk and is NOT covered by the repository's MIT
// license. See THIRD-PARTY-NOTICES.md for the full terms.
//
// Copyright (c) 2008-2016  Nagoya Institute of Technology
//                          Department of Computer Science
// All rights reserved.
//
// Source: open_jtalk-1.11/{jpcommon,njd2jpcommon}/*_rule_utf_8.h

/** [mora, consonant, vowel] in the original table order. */
export type MoraRow = [string, string, string | null];

// Order matters: lookup is a longest-prefix match performed by scanning top to
// bottom, exactly as the C does.
export const MORA_LIST: MoraRow[] = ${j(moraRows)};

/** Voiced vowel -> its devoiced counterpart. */
export const UNVOICE: Record<string, string> = ${j(unvoice)};

// jpcommon: descriptive name -> the numeric code that appears in the label
export const JP_POS: Record<string, string> = ${j(jpPos)};
export const JP_CFORM: Record<string, string> = ${j(jpCform)};
export const JP_CTYPE: Record<string, string> = ${j(jpCtype)};

/** njd2jpcommon: [pos, posGroup1, posGroup2, posGroup3, jpcommon name] */
export type NjdPosRow = [string, string, string, string, string];

export const NJD_POS: NjdPosRow[] = ${j(njdPos)};
export const NJD_CFORM: Record<string, string> = ${j(njdCform)};
export const NJD_CTYPE: Record<string, string> = ${j(njdCtype)};
`;

fs.writeFileSync(path.join(__dirname, '..', 'src', 'main', 'engine', 'tables.ts'), out);
console.log(`mora=${moraRows.length} unvoice=${Object.keys(unvoice).length} jpPos=${Object.keys(jpPos).length} njdPos=${njdPos.length}`);
